server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.21.16:3306/integral?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: 2007
  redis:
    host: 192.168.21.16
    port: 6379
